spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://43.201.144.113:3306/ewm
    username: root
    password: 6548

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect