#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mariadb://43.201.144.113:3306/ewm
#    username: root
#    password: 6548

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/ewm
    username: root
    password: taeyun1215

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 429886461497-r25e9nji15big5b2547osf93n3lm4ibe.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

#          kakao:
#            authorization-grant-type: authorization_code
#            client-id: 발급받은 키
#            client-secret: 발급받은 키
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            scope:
#              - profile_nickname
#              - account_email
#            client-authentication-method: POST
#            client-name: Kakao
#
#          naver:
#            client-id: 발급받은 키
#            client-secret: 발급받은 키
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name, email
#            client-name: Naver
#
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response