spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
