name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to user server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-user
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-user
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}

      - name: Deploy to mate server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-mate
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-mate
          host: ${{ secrets.HOST2 }}
          user: ec2-user
          key: ${{ secrets.KEY2 }}

      - name: Deploy to product server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-product
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-product
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}

      - name: Deploy to stock server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-stock
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-stock
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}

      - name: Deploy to order server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-order
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-order
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}

      - name: Deploy to api-gateway server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-apigateway
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-apigateway
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}

      - name: Deploy to eureka server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-eureka
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-eureka
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}