name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git log
        run: git log --name-only --oneline -1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle directories
        run: |
          for service in user-service mate-service product-service stock-service order-service
          do
            if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q $service; then
              echo "Building: $service"
              cd $service
              chmod +x gradlew
              ./gradlew bootJar
              cd -
            else
              echo "No modifications in $service directory, skip building."
            fi
          done
          
      - name: Check modified directories
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          for full_service_name in user-service mate-service product-service stock-service order-service
          do
            if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q $full_service_name; then
              service=${full_service_name%-service}  # Remove "-service" from the end of $full_service_name
              echo "Directory modified: $service"
              cd $full_service_name
              docker build -t ${{ secrets.DOCKER_REPO }}/ewm-$service .
              docker push ${{ secrets.DOCKER_REPO }}/ewm-$service
              cd -
            else
              echo "No modifications in $full_service_name directory"
            fi
          done
