name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy services
        uses: fifsky/ssh-action@master
        with:
          command: |
            for full_service_name in user-service mate-service product-service stock-service order-service apigateway-service eureka-service
            do
              if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q $full_service_name; then
                service=${full_service_name%-service}  # Remove "-service" from the end of $full_service_name
                echo "Docker image to be pulled: $service"
                docker rmi taeyun1215/ewm-$service
                docker pull ${{ secrets.DOCKER_REPO }}/ewm-$service
              else
                echo "No modifications in $full_service_name directory, skip docker rmi, pull."
              fi
            done
          host: ${{ secrets.HOST1 }}
          user: ec2-user
          key: ${{ secrets.KEY1 }}

      - name: Deploy to mate server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker rmi taeyun1215/ewm-mate
            docker pull ${{ secrets.DOCKER_REPO }}/ewm-mate
          host: ${{ secrets.HOST2 }}
          user: ec2-user
          key: ${{ secrets.KEY2 }}