name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: git log1
        run: git log --name-only --oneline -1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar

      - name: Check modified directories
        run: |
          if git log -1 --name-only ${{ github.sha }} -- 'user-service' | grep -q 'user-service'; then
            echo "Directory modified: user-service"
            cd user-service
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_REPO }}/ewm-user .
            docker push ${{ secrets.DOCKER_REPO }}/ewm-user
            cd -
          else
            echo "No modifications in user-service directory"
          fi

          if git log -1 --name-only ${{ github.sha }} -- 'mate-service' | grep -q 'mate-service'; then
            echo "Directory modified: mate-service"
            cd mate-service
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_REPO }}/ewm-mate .
            docker push ${{ secrets.DOCKER_REPO }}/ewm-mate
            cd -
          else
            echo "No modifications in mate-service directory"
          fi