server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ApiGateway-service
  cloud:
    gateway:
      routes:
        - uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - uri: lb://mate-service
          predicates:
            - Path=/mate-service/**
        - uri: lb://product-service
          predicates:
            - Path=/product-service/**
        - uri: lb://stock-service
          predicates:
            - Path=/stock-service/**
        - uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - uri: lb://order-aggregation-service
          predicates:
            - Path=/order-aggregation-service/**
